from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
PREFLIGHT = ROOT / "experiments" / "sem0" / "preflight_sem0_model.py"
EXPECTED = "667b0c1932bc6ffc593ed1d03f895bf2dc8dc6df21db3042284a6f4416b06a29"


def _load():
    spec = importlib.util.spec_from_file_location("sem0_preflight_test_module", PREFLIGHT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_parse_historical_ollama_version() -> None:
    module = _load()
    assert module.parse_ollama_version("ollama version is 0.21.2\n") == "0.21.2"
    assert module.parse_ollama_version("warning x 0.20.0\nollama version 0.21.2\n") == "0.21.2"


def test_parse_exact_historical_from_blob() -> None:
    module = _load()
    text = f'''# Modelfile generated by "ollama show"\nFROM /home/example/.ollama/models/blobs/sha256-{EXPECTED}\nTEMPLATE "x"\n'''
    assert module.parse_from_blob_sha256(text) == EXPECTED
    assert module.parse_from_blob_sha256(f"FROM sha256:{EXPECTED}\n") == EXPECTED


def test_multiple_distinct_blob_hashes_fail_closed() -> None:
    module = _load()
    other = "0" * 64
    with pytest.raises(ValueError, match="multiple distinct"):
        module.parse_from_blob_sha256(f"FROM sha256-{EXPECTED}\nFROM sha256-{other}\n")


def test_find_tag_requires_exact_model_name() -> None:
    module = _load()
    payload = {
        "models": [
            {"name": "llama3.1:8b", "model": "llama3.1:8b", "digest": "a" * 64},
            {"name": "llama3.1:latest", "model": "llama3.1:latest", "digest": "b" * 64},
        ]
    }
    tag = module.find_tag(payload, "llama3.1:8b")
    assert tag and tag["digest"] == "a" * 64
    assert module.find_tag(payload, "llama3.1:70b") is None


def test_preflight_passes_only_exact_historical_blob_and_runtime(monkeypatch) -> None:
    module = _load()
    monkeypatch.setattr(module, "run_command", lambda argv: (
        "ollama version is 0.21.2\n" if argv == ["ollama", "--version"]
        else f"FROM /tmp/blobs/sha256-{EXPECTED}\n"
    ))
    monkeypatch.setattr(module, "fetch_json", lambda url: {
        "models": [{"name": "llama3.1:8b", "model": "llama3.1:8b", "digest": "c" * 64}]
    })
    result = module.preflight()
    assert result["model_id"] == "llama3.1:8b"
    assert result["artifact_sha256"] == EXPECTED
    assert result["ollama_version"] == "0.21.2"
    assert result["checks"]["historical_blob_exact"] is True
    assert result["checks"]["historical_runtime_exact"] is True


def test_preflight_rejects_model_blob_change(monkeypatch) -> None:
    module = _load()
    changed = "1" * 64
    monkeypatch.setattr(module, "run_command", lambda argv: (
        "ollama version is 0.21.2\n" if argv == ["ollama", "--version"]
        else f"FROM /tmp/blobs/sha256-{changed}\n"
    ))
    monkeypatch.setattr(module, "fetch_json", lambda url: {
        "models": [{"name": "llama3.1:8b", "model": "llama3.1:8b", "digest": "c" * 64}]
    })
    with pytest.raises(ValueError, match="SEM0_MODEL_BLOB_MISMATCH"):
        module.preflight()


def test_preflight_rejects_runtime_change(monkeypatch) -> None:
    module = _load()
    monkeypatch.setattr(module, "run_command", lambda argv: (
        "ollama version is 0.22.0\n" if argv == ["ollama", "--version"]
        else f"FROM /tmp/blobs/sha256-{EXPECTED}\n"
    ))
    monkeypatch.setattr(module, "fetch_json", lambda url: {
        "models": [{"name": "llama3.1:8b", "model": "llama3.1:8b", "digest": "c" * 64}]
    })
    with pytest.raises(ValueError, match="SEM0_RUNTIME_MISMATCH"):
        module.preflight()
